---
title: "Final Writeup"
author: "Kadriye Sude Almus"
date: "10/25/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(dplyr)
library(broom)
library(stringr)
library(knitr)
library(nnet)
library(ggplot2)
library(MASS)
library(ISLR)
library(leaps)
install.packages("glmnet", repos = "http://cran.us.r-project.org")
library(glmnet)
install.packages("tree", repos = "http://cran.us.r-project.org")
library(pls)
install.packages('fastDummies')
library('fastDummies')
library(mgcv)
library(car)
```

### The Data

```{r}
data <- read.csv("data/data-train.csv")
```


### Final Model and Predictions

```{r}
attach(data)
set.seed(3)
train_ind <- sample(x = nrow(data), size = 0.8 * nrow(data))
test_ind_neg <- -train_ind
training <- data[train_ind, ]
testing <- data[test_ind_neg, ]
training
testing
ftraining <- training
ftesting <- testing
ftraining$Fr <- factor(ftraining$Fr, levels = c(0.052, 0.300, Inf))
ftraining$Re <- factor(ftraining$Re, levels = c(90, 224, 398))
ftesting$Fr <- factor(ftesting$Fr, levels = c(0.052, 0.300, Inf))
ftesting$Re <- factor(ftesting$Re, levels = c(90, 224, 398))


```


```{r}
fit.lm1 <- lm(log(R_moment_1) ~ (St + Re + Fr + Re*Fr), data = ftraining)
pred.lm1 <- predict(fit.lm1, ftesting)
plot(fit.lm1)
summary(fit.lm1)

mse_test1 <- mean((pred.lm1 - log(testing$R_moment_1))^2)
mse_test1

gam.m2 = gam(log(R_moment_2) ~ s(St) + Re + Fr + St:Re + St:Fr + Re:Fr, data = ftraining)
plot(gam.m2)
summary(gam.m2)
gam.check(gam.m2)

gam.m3 = gam(log(R_moment_3) ~ s(St) + Re + Fr + St:Re + St:Fr + Re:Fr, data = ftraining)
plot(gam.m3)
summary(gam.m3)
gam.check(gam.m3)

gam.m4 = gam(log(R_moment_4) ~ s(St) + Re + Fr + St:Re + St:Fr + Re:Fr, data = ftraining)
plot(gam.m4)
summary(gam.m4)
gam.check(gam.m4)

pred.gam2 <- predict(gam.m2, ftesting)
pred.gam3 <- predict(gam.m3, ftesting)
pred.gam4 <- predict(gam.m4, ftesting)

mse_gam2 <- mean((pred.gam2 - log(ftesting$R_moment_2))^2)
mse_gam3 <- mean((pred.gam3 - log(ftesting$R_moment_3))^2)
mse_gam4 <- mean((pred.gam4 - log(ftesting$R_moment_4))^2)

mse_gam2
mse_gam3
mse_gam4

```


### Predictions on the Test Data
```{r}
datat <- read.csv("data/data-test.csv")
datat$Fr <- factor(datat$Fr, levels = c(0.052, 0.300, Inf))
datat$Re <- factor(datat$Re, levels = c(90, 224, 398))

```

```{r}

predt.lm1 <- predict(fit.lm1, datat)
predt.gam2 <- predict(gam.m2, datat)
predt.gam3 <- predict(gam.m3, datat)
predt.gam4 <- predict(gam.m4, datat)

```

### Prediction Consolidation

Creating a csv of predictions:


```{r}
dataframe_all <- bind_rows(predt.lm1, predt.gam2, predt.gam3, predt.gam4)
dataframe_all <- exp(dataframe_all)
dataframe_all
write.csv(dataframe_all,"data/predictions.csv", row.names = FALSE)


```
